---
title: "eBird Records"
author: "Dax Kellie"
date: "16/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
# packages
library(tidyverse)
library(galah)
library(ggpubr) # for donutchart
library(pilot) # palette
library(showtext) # text for plot

font_add_google(name = "Lato")

showtext_auto()
```


```{r}
# Download data of frog records providers since 2016

taxa <- select_taxa("frogs")

providers <- ala_counts(taxa = taxa,
                        filters = select_filters(year > 2015),
                        group_by = select_fields("dataResourceName"))

# Wrangle
providers_brief <- providers %>%
  mutate(
    dataResourceName = case_when( # change groups
      dataResourceName == "FrogID"                ~ "FrogID",
      dataResourceName == "NSW BioNet Atlas"      ~ "NSW BioNet Atlas",
      dataResourceName == "iNaturalist Australia" ~ "iNaturalist Australia",
      TRUE                                        ~ "Other"
  )) %>%
  group_by(dataResourceName) %>%
  summarise_all(sum) %>% # condense rows and sum counts
  mutate(
    percent = round(((count / sum(count))*100), 0) # calculate percent
  )


# Plot
donut_providers <- ggdonutchart(providers_brief, "percent", 
             label = NA, 
             fill = "dataResourceName", 
             color = "white",
             palette = c(pilot::pilot_color("green"),
                         "#667073",
                         "#8B8680",
                         "#9E9E9F"),
             lab.pos = "in",
             font.family = "Lato",
             size = 1) +
  geom_text_pilot(mapping = aes(label = paste(percent, "%", sep = ""), fontface = "bold"),
            position = position_stack(vjust = 0.5),
            size = 15,
            family = "Lato",
            color = "white") +
  annotate_pilot( # Total Records
    x = 0.5,
    y = 0,
    label = paste(scales::comma((sum(providers_brief$count))), "\nFrog Records \nsince 2016"),
    color = "white",
    size = 13,
    family = "Lato",
    lineheight = 0.9
  ) +
  annotate_pilot( # FrogID
    x = 2.5,
    y = 90,
    hjust = 1.3,
    label = "FrogID",
    color = pilot::pilot_color("green"),
    family = "Lato",
    size = 17,
    fontface = "bold"
  ) +
  annotate_pilot( # iNaturalist
    x = 2.5,
    y = 45,
    hjust = 1.4,
    vjust = 2,
    label = "iNaturalist",
    color = "#9E9E9F",
    family = "Lato",
    size = 15
  ) +
  annotate_pilot( # NSW BioNet Atlas
    x = 2.5,
    y = 37,
    hjust = 0.22,
    vjust = 1.2,
    label = paste("NSW \nBioNet \nAtlas"),
    color = "#8B8680",
    family = "Lato",
    size = 15,
    lineheight = 0.6
  ) +
  annotate_pilot( # Other
    x = 2.5,
    y = 10,
    hjust = 0.001,
    vjust = 0,
    label = paste("Other"),
    color = "#D3D3D3",
    family = "Lato",
    size = 15
  ) +
  theme(legend.position = "none",
        text = element_text(size=20,  family="Lato", lineheight = 0.5),
        title = element_text(size = 23.5, family = "Lato", lineheight = 0.5),
        plot.margin = unit(c(t = 1, r = 3, b = 1, l = 2),"cm"),
        panel.background = element_rect(fill = "#222322", colour = "#222322"),
        plot.background = element_rect(fill = "#222322", colour = "#222322"))

donut_providers
```


```{r, eval = FALSE}
ggsave(here::here("comms", "2021-11-16_frogid", "plots", "donut_frogid.tiff"),
       width=9, height=9, dpi = 150)
```

