---
title: "total records"
author: "Dax"
date: "29/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
# remotes::install_github("AtlasOfLivingAustralia/galah@ala_counts")
library(galah)
library(tidyverse)
library(purrr)
library(viridis)
library(kableExtra)
library(pilot) # for colour palettes
```

```{r}
# Get data
galah_config(email = "dax.kellie@csiro.au")

search_fields("year") %>% View()

# filters <- select_filters(year > 1999)
fields <- select_fields(c("dataResourceName", "year"), expand = TRUE)

providers <- ala_counts(group_by = fields, limit = 1e5)
providers_total <- ala_counts(group_by = "year", limit = 1e5)

# wrangle
providers_total <- providers_total %>% 
  rename(total_count = count) %>% # rename
  mutate(year = as.integer(year)) # change class

# get cumulative sum
providers_total <- providers_total %>% 
  arrange(-desc(year)) %>%
  mutate(cumulative_count = cumsum(total_count))

# merge
providers <- providers %>% 
  mutate(year = as.integer(year)) %>% # match class of providers_total
  left_join(providers_total, by = "year")
```


```{r}
# Basis of record
galah::find_field_values("basisOfRecord")

# Counts of human observations
human_obs <- ala_counts(filters = select_filters(basisOfRecord = "HUMAN_OBSERVATION"), 
                        group_by = "year", 
                        limit = 1e4)

# Counts of specimen observations
specimen_obs <- ala_counts(filters = select_filters(basisOfRecord = "PRESERVED_SPECIMEN"), 
                        group_by = "year", 
                        limit = 1e4)

# cumulative counts
human_obs <- human_obs %>%
  mutate(year = as.integer(year)) %>% # change class
  arrange(-desc(year)) %>%
  mutate(cumulative_count = cumsum(count))  

specimen_obs <- specimen_obs %>%
  mutate(year = as.integer(year)) %>% # change class
  arrange(-desc(year)) %>%
  mutate(cumulative_count = cumsum(count))  

# rename
# human_obs <- human_obs %>% rename(human_count = count)
# specimen_obs <- specimen_obs %>% rename(specimen_count = count)

```

```{r}
labels <- c("Total", "Human \nObservations", "Museum Specimens")

# Set font for {pilot} titles
pilot::set_pilot_family("Lato", title_family = "Lato") # Set font

# Plot
ggplot() + 
  geom_line(data = providers, 
            mapping = aes(x = year, y = cumulative_count), 
            size = 2,
            colour = "#E06E53") +
  geom_line(data = human_obs,
            mapping = aes(x = year, y = cumulative_count),
            size = 1.3,
            linetype = "dashed",
            alpha = 0.8,
            colour = "#667073") +
  geom_line(data = specimen_obs,
            mapping = aes(x = year, y = cumulative_count),
            size = 1.3,
            linetype = "dashed",
            alpha = 0.8,
            colour = "#9E9E9F") +
  xlim(c(1950,2021)) +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,100000000),
                     labels = scales::comma) +
  labs(x = "Year",
       y = "Records in ALA") +
  annotate_pilot(x = 1995, y = 40e6, label = labels[1], color = "#E06E53", size = 6) +
  annotate_pilot(x = 2014, y = 30e6, label = labels[2], color = "#667073", size = 4.5) +
  annotate_pilot(x = 2003, y = 5e6, label = labels[3], color = "#9E9E9F", size = 4.5) +
  theme_pilot()

here::here()
ggsave(here::here("projects", "citizen-science", "line-plot_total-records.png"))
```

