# Common names of broad plantae groups and taxonomic families

# packages
library(tidyverse)
library(here)
library(readxl)

#----------------#

# Larger groups

# download spreadsheet
groups <- read_xlsx(here("comms", "2024-09-25_plantae", "SpeciesGroups_ALA.xlsx"),
                    sheet = 1)

groups_clean <- groups |>
  slice(-1) |>
  filter(!str_detect(Inclusions, "Equisetopsida")) |> # Vascular plants groups override smaller groups
  mutate(
    common_name = case_when(
      !is.na(level2Name) ~ level2Name,
      is.na(level2Name)  ~ level3Name,
      .default = NA
    ),
    includes = strsplit(as.character(Inclusions), ",")
  ) |>
  unnest(includes) |>
  select(common_name, includes) |>
  mutate(
    includes = str_trim(includes)
  ) |>
  filter(common_name != "Horsetails") |> # includes is NA, which affects the next step
  tibble::add_row(includes = NA, common_name = "Other")


#----------------#

# Family names

# generated from chatgpt (but it broke at ~160)
family_common_names <- tribble(
  ~family,        ~family_common_name,
  "Fabaceae",     "Wattles and relatives",
  "Asteraceae",   "Daisies",
  "Myrtaceae",    "Gum trees, tea trees and relatives",
  "Poaceae",      "Grasses",
  "Orchidaceae",  "Orchids",
  "Proteaceae",   "Banksias, grevilleas and hakeas",
  "Solanaceae",   "Nightshades",
  "Ericaceae",    "Heaths",
  "Rosaceae",     "Rosaceae",
  "Cyperaceae",   "Sedges",
  "Asparagaceae", "Lomandras and relatives",
  "Chenopodiaceae", "Saltbushes",
  "Rutaceae",     "Boronia and citrus relatives",
  "Malvaceae",    "Hibiscus and mallows",
  "Lamiaceae",    "Mints",
  "Apocynaceae",  "Apocynaceae",
  "Pittosporaceae","Pittosporums",
  "Euphorbiaceae","Spurges",
  "Goodeniaceae", "Goodenias and dampieras",
  "Sapindaceae",  "Hopbushes and tamarinds",
  "Droseraceae",  "Sundews",
  "Rubiaceae",    "Coffee relatives",
  "Dilleniaceae", "Dilleniaceae",
  "Oleaceae",     "Olives and jasmines",
  "Rhamnaceae",   "Australian buckthorns",
  "Amaranthaceae","Saltbushes and goosefoots",
  "Casuarinaceae","She-oaks",
  "Convolvulaceae","Bindweeds and morning glories",
  "Cactaceae",    "Cacti",
  "Acanthaceae",  "Acanthaceae",
  "Araliaceae",   "Aralia relatives",
  "Hemerocallidaceae","Hemerocallids",
  "Verbenaceae",  "Verbenas and relatives",
  "Apiaceae",     "Carrots and umbellifers",
  "Scrophulariaceae","Figworts and related herbs",
  "Lauraceae",    "Laurels",
  "Campanulaceae","Bellflowers and lobelias",
  "Pteridaceae",  "Brake and maidenhair ferns",
  "Plantaginaceae","Plantains and related herbs",
  "Polygonaceae", "Docks and knotweeds",
  "Thymelaeaceae","Pimeleas and daphne relatives",
  "Ranunculaceae","Buttercups",
  "Phyllanthaceae","Phyllanthaceae",
  "Santalaceae",  "Sandalwoods and quandongs",
  "Loranthaceae", "Mistletoes",
  "Moraceae",     "Figs and mulberries",
  "Iridaceae",    "Irises and patersonias",
  "Geraniaceae",  "Geraniums and pelargoniums",
  "Dennstaedtiaceae","Bracken ferns",
  "Hypericaceae", "St. John’s worts",
  "Violaceae",    "Violets",
  "Aizoaceae",    "Pigfaces and ice-plants",
  "Boraginaceae", "Forget-me-nots and relatives",
  "Blechnaceae",  "Hard and water ferns",
  "Brassicaceae", "Mustards and cresses",
  "Bignoniaceae", "Trumpet vines",
  "Oxalidaceae",  "Wood sorrels",
  "Commelinaceae","Commelinas and spiderworts",
  "Xanthorrhoeaceae","Grass trees and Asphodels",
  "Primulaceae",  "Primroses",
  "Polypodiaceae","Polypod ferns",
  "Elaeocarpaceae","Quandongs and blue-berry relatives",
  "Juncaceae",    "Rushes",
  "Arecaceae",    "Palms",
  "Onagraceae",   "Evening primroses",
  "Haloragaceae", "Raspworts and water-milfoils",
  "Crassulaceae", "Stonecrops",
  "Colchicaceae", "Colchicaceae",
  "Araceae",      "Aroids",
  "Passifloraceae","Passionflowers",
  "Vitaceae",     "Grapevines",
  "Stylidiaceae", "Triggerplants",
  "Polygalaceae", "Milkworts",
  "Pottiaceae",   "Pott mosses",
  "Cunoniaceae",  "Coachwoods and callicomas",
  "Caryophyllaceae","Pinks and carnations",
  "Celastraceae", "Celastraceae (spindles)",
  "Urticaceae",   "Nettles",
  "Cupressaceae", "Cypresses and callitris",
  "Meliaceae",    "Mahoganies and cedrela relatives",
  "Portulacaceae","Purslanes and pigweeds",
  "Cannabaceae",  "Hemp and hop relatives",
  "Gleicheniaceae","Coral ferns",
  "Cyatheaceae",  "Tree ferns (Cyatheas)",
  "Polytrichaceae","Haircap mosses",
  "Restionaceae", "Restios and cord-rushes",
  "Aspleniaceae", "Spleenworts",
  "Leucobryaceae", "Leucobryum and related mosses",
  "Smilacaceae",  "Smilaxes and catbriers",
  "Menispermaceae","Moonseeds and climbers",
  "Dicksoniaceae","Soft tree ferns (Dicksonias)",
  "Dryopteridaceae","Wood ferns",
  "Bryaceae",     "Bryum and mosses",
  "Cucurbitaceae","Gourds and cucumbers",
  "Gentianaceae", "Gentians",
  "Asphodelaceae","Bulbine lilies and aloes",
  "Anacardiaceae","Cashews and wattles (some natives)",
  "Hydrocharitaceae","Waterweeds",
  "Lentibulariaceae","Bladderworts and carnivorous herbs",
  "Papaveraceae","Poppies",
  "Amaryllidaceae","Amaryllids and onion-relatives",
  "Zamiaceae",    "Cycads",
  "Zygophyllaceae","Caltrops and tribulus relatives",
  "Caprifoliaceae", "Honeysuckles and related shrubs",
  "Basellaceae",  "Basellas and climbing succulents",
  "Monimiaceae",  "Monimiaceae (wilkiea relatives)",
  "Lindsaeaceae", "Lindsays and delicate ferns",
  "Hymenophyllaceae", "Filmy ferns",
  "Ochnaceae",    "Ochna relatives",
  "Loganiaceae",  "Logania and relatives",
  "Lophocoleaceae", "Lophocolea liverworts",
  "Salicaceae",   "Willows and poplars",
  "Phytolaccaceae", "Pokeweeds",
  "Haemodoraceae", "Kangaroo paws and bloodroots",
  "Lythraceae",   "Loosestrifes and melastome relatives",
  "Pandanaceae",  "Screwpines (Pandanus)",
  "Picrodendraceae", "Picrodendraceae",
  "Salviniaceae", "Floating water ferns (Salvinia)",
  "Zingiberaceae", "Gingers",
  "Hypoxidaceae", "Hypoxidaceae (star grasses)",
  "Sapotaceae",   "Planchonellas and quandong relatives",
  "Araucariaceae","Bunyas, hoop pines and kauri relatives",
  "Viburnaceae",  "Viburnums",
  "Hypnaceae",    "Feather mosses",
  "Rhizophoraceae", "Mangroves",
  "Alliaceae",    "Onions and relatives",
  "Nothofagaceae","Southern beeches",
  "Thuidiaceae",  "Thuidium feather mosses",
  "Brachytheciaceae", "Feather mosses (Brachythecium group)",
  "Lunulariaceae", "Crescent-cup liverworts",
  "Winteraceae",  "Winteraceae (native pepperbushes)",
  "Ricciaceae",   "Crystalworts and simple liverworts",
  "Capparaceae",  "Capparis and caper relatives",
  "Juncaginaceae", "Arrowgrasses and sea rushes",
  "Pinaceae",     "Pines and fir relatives",
  "Nyctaginaceae","Four-o'clocks and bougainvillea relatives",
  "Atherospermataceae", "Southern sassafras and laurels",
  "Typhaceae",    "Bulrushes and cattails",
  "Bartramiaceae", "Bartramia mosses",
  "Pontederiaceae","Pickerelweeds and aquatic herbs",
  "Selaginellaceae","Spikemosses",
  "Piperaceae",   "Peppers and pepper vines",
  "Caulerpaceae", "Caulerpas (seaweeds)",
  "Dioscoreaceae","Yams and dioscorea relatives",
  "Hypopterygiaceae", "Hypopterygiaceae (feather mosses)",
  "Melastomataceae","Melastomes and related shrubs",
  "Lycopodiaceae","Clubmosses",
  "Ebenaceae",    "Ebonies and persimmon relatives",
  "Menyanthaceae","Buckbeans and water fringe herbs",
  "Podocarpaceae","Podocarps (ancient conifers)",
  "Dicranaceae",  "Dicranum mosses",
  "Alismataceae", "Water plantains",
  "Nymphaeaceae", "Water lilies",
  "Aquifoliaceae","Hollies",
  "Plumbaginaceae","Leadworts and thrift relatives",
  "Marsileaceae", "Nardoo and aquatic ferns",
  "Lomariopsidaceae", "Lomariopsid ferns",
  "Eupomatiaceae","Eupomatia and native guavas",
  "Ripogonaceae", "Ripogonums (supplejacks)",
  "Corallinaceae","Coralline algae",
  "Magnoliaceae", "Magnolias",
  "Garryaceae",   "Silk-tassels and garrya relatives",
  "Trapaceae",    "Water chestnuts and aquatic sedges",
  "Equisetaceae", "Horsetails",
  "Glaucocystaceae","Glaucocystophyte algae",
  "Atherospermataceae","Southern sassafras",
  "Araceae","Aroids",
  "Aspleniaceae","Spleenworts",
  "Baloskionaceae","Baloskion and restio-like rushes",
  "Buxaceae","Box relatives",
  "Cabombaceae","Water shield family",
  "Calceolariaceae","Slipperflowers and related herbs",
  "Cistaceae","Rockroses",
  "Clusiaceae","St. John's bread relatives",
  "Cneoraceae","Cneorum relatives",
  "Daphniphyllaceae","Daphniphyllum relatives",
  "Euphorbiaceae","Spurges",
  "Fumariaceae","Fumitories and bleeding-hearts",
  "Hamamelidaceae","Witch-hazels and native hazels",
  "Illiciaceae","Star anise relatives",
  "Krameriaceae","Krameria root parasites",
  "Lamiaceae","Mints and aromatic herbs",
  "Malpighiaceae","Malpighias and relatives",
  "Myrsinaceae","Myrsine and shrub relatives",
  "Nelumbonaceae","Lotus family",
  "Orobanchaceae","Broomrapes and parasitic herbs",
  "Proteaceae","Banksias, grevilleas and hakeas",
  "Restionaceae","Restios and cord-rushes",
  "Saxifragaceae","Saxifrages and mountain herbs",
  "Thelypteridaceae","Thelypterid ferns",
  "Ulmaceae","Elms and related trees",
  "Verbenaceae","Verbenas",
  "Wilsoniaceae","Wilsonia and coastal herbs",
  "Xyridaceae","Yellow-eyed grasses",
  "Zannichelliaceae","Sea grass relatives"
)