---
title: "Atlas of Living Australia: Research impact summary"
format: 
  dashboard:
    orientation: rows
---

## Row {height= 10%}


```{r}
#| message: false
#| warning: false
#| echo: false
library(here)
library(tidyverse)
library(janitor)
library(lubridate)
```

```{r}
#| message: false
#| warning: false
#| echo: false
data <- read_csv(here("projects", "literature-tracking", "data", "2025-03-05_publications.csv"))
```

```{r}
#| message: false
#| warning: false
#| echo: false
dataclean <- janitor ::clean_names(data) 
```


```{r}
#| message: false
#| warning: false
#| echo: false
dataclean2 <- dataclean |>
  mutate(
    date_added_clean = as_date(date_added),
    date_added_month = month(date_added_clean),
    date_added_year = year(date_added_clean)) |>
   select(title, date, place, publication_year, publication_title, item_type, url, manual_tags, date_added, date_added_clean, date_added_month, date_added_year)
```

```{r}
#| message: false
#| warning: false
#| echo: false
remove <- c("1 - ", "2 - ", "3 - ", "4 - ", "5 - ", "6 - ") # list numbers you want removed

dataclean3 <- dataclean2 |> # remove numbers
  mutate( # make new column called "tags"
    tags = str_remove_all(dataclean2$manual_tags, # remove prefix
                          paste(remove, collapse = "|")) 
  )
```

```{r}
#| message: false
#| warning: false
#| echo: false
## Filtering Tags

# separate manual tags into separate rows (multiple entries for one paper if inc. many tags)
ALA_tags <- dataclean3 %>%
  mutate(tags = strsplit(as.character(tags), ";")) %>% # split names where there is a semicolon
  unnest(tags) # make them occupy multiple rows

# trim whitespace from tags
ALA_tags <- ALA_tags %>% # remove numbers
  mutate(
    tags = str_trim(tags) # trim whitespace around string 
  )
```

```{r}
#| message: false
#| warning: false
#| echo: false
#number of publications that cite the ALA (all time)

totalpublications <- (nrow(dataclean2))
```


```{r}
#| message: false
#| warning: false
#| echo: false
#number of papers that cite the ALA (all time)
cited_papers <- ALA_tags |>
  filter(tags == "ALA cited") |> 
  filter(item_type == "journalArticle")
```

```{r}
#| message: false
#| echo: false
#| warning: false
# number of papers that use ALA data (all time)
used_papers <- ALA_tags |>
  filter(tags == "ALA used") |>
  filter(item_type == "journalArticle")
```

```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false

# number of papers that either cite or use the ALA (all time)
cited_used_papers <- nrow(cited_papers) + nrow(used_papers)
```



```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false

# create a tibble of the used and cited papers so we can make a bar plot later 
cited_used_papers_tibble <- full_join(cited_papers, used_papers)
```


```{r}
#| message: false
#| warning: false
#| echo: false
#number of reports that cite the ALA (all time)
cited_reports <- ALA_tags |>
  filter(tags == "ALA cited") |> 
  filter(item_type == "report")
```


```{r}
#| message: false
#| echo: false
#| warning: false
# number of reports that use ALA data (all time)
used_reports <- ALA_tags |>
  filter(tags == "ALA used") |>
  filter(item_type == "report")
```


```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false

## ** INCLUDE **

# number of reports that either cite or use the ALA (all time)
cited_used_reports <- nrow(cited_reports) + nrow(used_reports)
```




```{r}
# Repeat steps above but for last year only 
#| message: false
#| warning: false
#| echo: false
used <- ALA_tags |>
  filter(tags == "ALA used" | tags %in% c("AGRICULTURE", "BIODIVERSITY SCIENCE", "BIOGEOGRAPHY", "CITIZEN SCIENCE", "CLIMATE CHANGE", "CONSERVATION", "DATA MANAGMENT", "DNA", "ECOLOGY", "ECOSYSTEM SERVICES", "EVOLUTION", "INVASIVE SPECIES", "MARINE", "PHYLOGENETICS", "SPECIES DISTRIBUTION", "TAXONOMY"))
```

```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false
tag_counts <- ALA_tags |>
  group_by(tags) |>
  summarise(count = n()) 

  
selected_tags <- c("AGRICULTURE", "BIODIVERSITY SCIENCE", "BIOGEOGRAPHY", "CITIZEN SCIENCE", "CLIMATE CHANGE", "CONSERVATION", "DATA MANAGMENT", "DNA", "ECOLOGY", "ECOSYSTEM SERVICES", "EVOLUTION", "INVASIVE SPECIES", "MARINE", "PHYLOGENETICS", "SPECIES DISTRIBUTION", "TAXONOMY")

filtered_tags <- tag_counts %>%
  filter(tags %in% selected_tags)
```

```{r}
#| message: false
#| warning: false
#| echo: false
total_tags <- sum(filtered_tags$count)
```

```{r}
#| message: false
#| warning: false
#| echo: false
percents <- filtered_tags %>%
  mutate(perc = paste0(sprintf("%4.1f", count / total_tags * 100), "%"))
```

```{r}
#| message: false
#| warning: false
#| echo: false
numeric_percentages <- as.numeric(sub("%", "", percents$perc))

# Sum the numeric percentages
total_sum <- sum(numeric_percentages)
```

```{r}
#| message: false
#| warning: false
#| echo: false
percents <- percents %>%
  mutate(tags = reorder(tags, count))
```

```{r}
#| message: false
#| warning: false
#| echo: false
top_10 <- percents %>%
  top_n(10, wt = count)
```


```{r}
# Repeat steps above but for last year only 
dataclean4 <- dataclean3 |> 
  filter(date_added_clean >= ymd("2024-01-01")) |>
  filter(date_added_clean <= ymd("2024-12-31")) |>
  filter(publication_year == c("2024")) 
```

```{r}
#| message: false
#| warning: false
#| echo: false
## Filtering Tags

# separate manual tags into separate rows (multiple entries for one paper if inc. many tags)
ALA_tags <- dataclean4 %>%
  mutate(tags = strsplit(as.character(tags), ";")) %>% # split names where there is a semicolon
  unnest(tags) # make them occupy multiple rows

# trim whitespace from tags
ALA_tags <- ALA_tags %>% # remove numbers
  mutate(
    tags = str_trim(tags) # trim whitespace around string 
  )
```

```{r}
#| message: false
#| warning: false
#| echo: false
#number of *papers* that cite the ALA in last year
cited_papers_year <- ALA_tags |>
  filter(tags == "ALA cited") |>
  filter(item_type =="journalArticle")
```


```{r}
#| message: false
#| echo: false
#| warning: false
# number of *papers* that use the ALA in last year
used_papers_year <- ALA_tags |>
  filter(tags == "ALA used") |>
  filter(item_type == "journalArticle") 
```


```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false

# *papers or journal articles* cited and used in last year

used_cited_papers_year <- nrow(used_papers_year) + nrow(cited_papers_year)
```

```{r}
#| message: false
#| echo: false
#| warning: false
# number of *reports* that use the ALA in last year
used_reports_year <- ALA_tags |>
  filter(tags == "ALA used") |>
  filter(item_type == "report") 
```


```{r}
#| message: false
#| warning: false
#| echo: false
#number of *reports* that cite the ALA in last year
cited_reports_year <- ALA_tags |>
  filter(tags == "ALA cited") |>
  filter(item_type =="report")
```


```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false

# *reports* cited and used in the last year

used_cited_reports_year <- nrow(cited_reports_year) + nrow(used_reports_year)
```



```{r}
#| content: valuebox
#| title: "Publications citing, using or mentioning the Atlas"

### FILL THESE VALUES IN W ABOVE NUMBERS 

totalpub <- totalpublications |> scales::comma()

list(
  icon = "book-half",
  color = "#EEECEA",
  value = totalpub
)
```


```{r}
#| content: valuebox
#| title: "Journal articles citing or using the Atlas"

### FILL THESE VALUES IN W ABOVE NUMBERS 

totalarticles <- cited_used_papers |> scales::comma()
list(
  icon = "book-half",
  color = "#EEECEA",
  value = totalarticles
)
```



```{r}
#| content: valuebox
#| title: "Journal articles citing or using the Atlas (2024)"

### FILL THESE VALUES IN W ABOVE NUMBERS 

articles23 <- used_cited_papers_year |> scales::comma()

list(
  icon = "book-half",
  color = "#EEECEA",
  value = articles23
)
```


```{r}
#| content: valuebox
#| title: "Reports citing or using the Atlas"

### FILL THESE VALUES IN W ABOVE NUMBERS 

totalreports <- cited_used_reports |> scales::comma()
list(
  icon = "book-half",
  color = "#EEECEA",
  value = totalreports
)
```


```{r}
#| content: valuebox
#| title: "Reports citing or using the Atlas (2024)"

### FILL THESE VALUES IN W ABOVE NUMBERS 

articles23 <- used_cited_reports_year |> scales::comma()

list(
  icon = "book-half",
  color = "#EEECEA",
  value = articles23
)
```



## Row {height=90%}

```{r}
#| message: false
#| warning: false
#| echo: false
custom_palette <- c("#003A70", "#6CDE4B", "#DE4BC3", "#F26649", "#E0AA51", "#895C81", "#667073", "#691C32", "#6BDAD5", "#B7CD96")
```


```{r}
#| message: false
#| warning: false
#| echo: false

library(pilot)
litsum <- extrafont::loadfonts(device = "win", quiet = TRUE)
theme_set(theme_minimal(base_family = "Roboto"))

litsum <- ggplot(top_10, aes(x = count, y = tags)) +
  geom_col(fill = custom_palette) +
  geom_text(
    aes(label = paste(tags, perc, sep = "\n")),
    position = position_nudge(x = -0.5),
    hjust = 1,
    vjust = 0.5,  # Center the label vertically
    color = "white", size = 2.5, fontface = "bold") +  # Adjust text color, size, and fontface for bold
  theme_pilot(axes = "",
              grid = "",
              legend_position = "none") + # Set font family, text color, and bold
  scale_fill_manual(values = custom_palette) + 
  labs(caption = "*TOP JOURNAL RESEARCH CATEGORIES (2024)") +
  theme(axis.text.x = element_blank(),  
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())  


```


```{r}
#| title: Top journal research categories of 2024
#| echo: false
plot(litsum)
```

```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false
apublicationbyyear <- dataclean2 |>
  filter(item_type == "journalArticle") |>
  filter(publication_year < 2026) |>
  group_by(publication_year) |>
  count() 
```


```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false
# change the date range of the tag code so it can be used again but this time across all years and for ALA tools 
dataclean3 <- dataclean2 |> 
  filter(date_added_clean >= ymd("2007-01-01")) |>
  filter(date_added_clean <= ymd("2025-12-31"))
```

```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false
remove <- c("1 - ", "2 - ", "3 - ", "4 - ", "5 - ", "6 - ") # list numbers you want removed

dataclean4 <- dataclean3 %>% # remove numbers
  mutate( # make new column called "tags"
    tags = str_remove_all(dataclean3$manual_tags, # remove prefix
                          paste(remove, collapse = "|")) 
  )
```

```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false
## Filtering Tags

# separate manual tags into separate rows (multiple entries for one paper if inc. many tags)
ALA_tags <- dataclean4 %>%
  mutate(tags = strsplit(as.character(tags), ";")) %>% # split names where there is a semicolon
  unnest(tags) # make them occupy multiple rows

# trim whitespace from tags
ALA_tags <- ALA_tags %>% # remove numbers
  mutate(
    tags = str_trim(tags) # trim whitespace around string 
  )
```




```{r}
#| include: false
#| message: false
#| warning: false
#| echo: false

tool_tag_counts <- ALA_tags |>
  group_by(tags, publication_year) |>
  summarise(tag_count = n()) 

selected_tool_tags <- c("Species occurrence records", "galah", "Spatial Portal", "Species lists", "Profiles", "Climate Data", "Images", "Survey Planning", "AusTraits", "APPD", "AVH", "BioCollect", "Digivol", "Sensitive Data Service SDS", "Modelling", "Phylolink", "Habitat Condition Assessment Tool", "delta") #tool tags

filtered_tags <- tool_tag_counts %>%
  filter(tags %in% selected_tool_tags)

apublicationbyyear <- merge(filtered_tags, apublicationbyyear) |>
  rename(total_publications = n)
apublicationbyyear


apublicationbyyear <- apublicationbyyear |>
  group_by(publication_year) |>
  mutate(nil_tags = total_publications - sum(tag_count))
  

# apublicationbyyear2 <- apublicationbyyear |>
#   # Create a row for 'nil' tags and associate it with nil_tags values
#   bind_rows(
#     apublicationbyyear |>
#       mutate(tags = "nil", tag_count = nil_tags) |>
#       select(publication_year, tags, tag_count))
```


```{r}
#| title: Tools cited in the publication tracker (bar plot)
#| echo: false


apublicationbyyear$publication_year <- as.character(apublicationbyyear$publication_year)

tagsplot <- ggplot(apublicationbyyear, aes(x = publication_year, y = tag_count, fill = tags)) + 
  geom_bar(stat = "identity", position = "stack", size = 0.5, width = 0.98) + 
  labs(x = "", 
       y = "Total papers tagged") +
  pilot::theme_pilot(grid = "h") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_discrete(breaks = c(2007, 2009, 2011, 2013, 2015, 2017, 2019, 2021, 2023, 2025)) +
  scale_fill_pilot(palette = "seven", discrete = TRUE, reverse = FALSE) + 
  #labs(caption = "*NO. OF JOURNAL ARTICLES BY YEAR") +
  theme(
    panel.grid = element_blank(),
    axis.line.y = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    legend.key.width = unit(1, 'mm')) 

```


```{r}
ggsave(tagsplot, file = here::here("stacked-tags-bar-plot.png"),
       height = 7, width = 10)
```

```{r}
piccia_palette <- c(
  purple = "#5c1c8d",
lilac = "#be77bf",
dark_pink = "#cd0d72",
light_pink = "#f76bcc",
orange = "#b4612b",
emerald = "#3ca465",
forest_green = "#1c4d3b",
blue_grey = "#55517e",
soft_coral = "#FF6F61",
seafoam_green = "#A8E6CF",
dusty_lavender = "#B49CC2",
muted_gold = "#D4AF37",
slate_blue = "#6A7F9B",
burnt_sienna = "#E97451",
soft_peach = "#FAD02E",
charcoal_grey = "#333333",
periwinkle_blue = "#8E9BFF",
mint_green = "#98FF98")
```


```{r}
theme_piccia <- function() {
  
  theme_minimal(base_size = 12) +
    # Align the font with the rest of the page
    theme(text = element_text(family = "Roboto", colour = "#12051C"),
          # Make the title the main thing, and make it wrap to the width of the plot
          # by putting it inside a textbox
          plot.title = ggtext::element_textbox_simple(face = "bold", size = rel(1.5),
                                                      margin = margin(12, 0, 12, 0, "pt")),
          axis.text = element_text(family = "Roboto", colour = "#372D40"),
          panel.grid = element_line(colour = "#FFFFFF"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor = element_blank(),
          axis.title = element_blank(),
          plot.background = element_rect(colour = "#F7F4F6", fill = "#F7F4F6"),
          # Give everything a bit more space
          plot.margin = margin(rep(12, 4)))
}
```


```{r, fig.width=20, fig.height=20}
#| title: "Tools cited as used"

apublicationbyyear <- apublicationbyyear |>
  filter(publication_year != 2025) 


tagslineplot <- 
  apublicationbyyear |>
  ggplot(aes(x = publication_year,
             y = tag_count,
             colour = tags,
             group = tags)) +  
  geom_line(linewidth = 5,
            alpha = 0.85) +
  pilot::theme_pilot(grid = "h") +
  scale_y_log10(expand = c(0, 0)) +  
  scale_x_discrete(breaks = c(2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020, 2022, 2024)) + 
  scale_fill_pilot(palette = "seven", discrete = TRUE, reverse = FALSE) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_text(size = 8),
        panel.spacing.x = unit(8, "pt"),
        panel.spacing.y = unit(8, "pt")) +
  gghighlight::gghighlight(
    unhighlighted_params = list(alpha = 0.1,
                                linewidth = 0.5,
                                colour = piccia_palette[["blue_grey"]])
  ) +     
  facet_wrap(. ~ tags, nrow = 6, ncol = 3) +
  coord_fixed(ratio = 6) +  
  theme(strip.text = element_blank()) +
  labs(y = expression("No. tagged papers (log"[10]*")"),
       x = "Publication year") 


tagslineplot


```


```{r}
#| include: false
apublicationbyyear |>
  filter(tags %in% c("delta", "Sensitive data service", "Habitat Condition Assessment Tool", "AusTraits"))
```


```{r}
ggsave("tags_lineplot.png", plot = tagslineplot, width = 16, height = 10)

```


```{r}
#| title: "Journal articles citing or using ALA data by year"

publication_counts <- cited_used_papers_tibble |> #used this tibble instead of apublicationbyyear: multiple rows for each year not plotting 
  count(publication_year) |>
   filter(publication_year != 2025) 

publication_counts$publication_year <- as.factor(publication_counts$publication_year)

pubsyearbargraph <- ggplot(publication_counts, aes(x = publication_year, y = n)) + 
  geom_bar(stat = "identity", size = 0.5, width = 0.98) + 
  labs(x = "Year", 
       y = "Total journal articles") +
  pilot::theme_pilot(grid = "h") +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_discrete(breaks = c(2007, 2009, 2011, 2013, 2015, 2017, 2019, 2021, 2023, 2025)) +
  labs(caption = "*TOTAL JOURNAL ARTICLES CITING OR USING ALA DATA") +
  theme(
    panel.grid = element_blank(),
    axis.line.y = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    legend.key.width = unit(1, 'mm')) 
pubsyearbargraph
```




